name = "ai-proxy-worker"
main = "src/index.js"
compatibility_date = "2024-05-01"

[vars]
# استخدم نفس كلمة السر القوية التي اخترتها من قبل
SECRET_KEY = "YOUR_STRONG_PASSWORD"

[[services]]
binding = "AI_WORKER"
service = "actual-ai-worker-ammar" # <-- تأكد من أن هذا هو اسم الـ Worker الصحيح
